name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: Style checks
#      run: sbt styleCheck
    - name: Install NPM Dependencies
#      run: npm install; cd native; npm install; cd ..
      run: npm install
    - name: Test with SBT (fastopt)
      run: sbt test
#    - name: Test with SBT (fullopt)
#      run: sbt "set Global/scalaJSStage := FullOptStage" test
